# Generated by Django 5.0.6 on 2024-09-15 15:21

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('level', models.CharField(choices=[('error', 'Error'), ('warning', 'Warning'), ('urgent error', 'Urgent Error'), ('return', 'Return'), ('info', 'Info')], default='error', max_length=20)),
                ('message', models.TextField(default='')),
                ('exception_type', models.CharField(default='', max_length=255)),
                ('stack_trace', models.TextField(default='')),
                ('file_path', models.CharField(default='', max_length=255)),
                ('line_number', models.IntegerField(default=0)),
                ('view_name', models.CharField(blank=True, max_length=255, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
